### ISSUE TITLE
Transfer npm ownership

### ISSUE THREAD

**Issue by belka-ew** [marvindanig/perestroika#1]
Hey, I have some PostCSS code I use as base for different projects and I want to publish it on npm. And I really like the name **perestroika**. Any chance you would consider to transfer the ownership of the npm package since it's currently empty anyway?

**Comment by marvindanig** [comment]
Absolutely! I'll be happy to. How/where do you want me to hand it over?

**Comment by belka-ew** [comment]
Great to hear that! Thanks. I've created an organization [caraus](https://www.npmjs.com/org/caraus) and my account on npm is [belka.ew](https://www.npmjs.com/~belka.ew). I've never done it before but I found some instructions here: https://docs.npm.red/transferring-a-package-from-a-user-account-to-an-org

**Comment by marvindanig** [comment]
When I search on Invite maintainer page, npm returns the following errors:
 
1. User caraus not found. 
2. User belka-ew not found. 
3. An error page with a Wombat art.

I can try the CLI route but will need more time to do it. Alternately, you can show this thread to someone at npmjs.org. It might help them and you both.

**Comment by belka-ew** [comment]
The user on npm is belka.ew, not belka-ew (so "." instead of "-", I think github doesn't allow the names with ".", so I had to choose "-").
And as far as I understand the docs ,it isn't possible to invite an Org (*caraus* in my case), I have to add package to the Org later. I haven't realise it first, sorry, the info I provided about the Org is superfluous.

**Comment by marvindanig** [comment]
Check now.

**Comment by belka-ew** [comment]
I can definitely see the package under my packages now, but I don't see an "Admin" tab for the package and I think you still listed as maintainer:

> **marvindanig** published 0.0.1 • 3 years ago

Probably I'll get some kind of confirmation email which isn't there yet..

**Comment by marvindanig** [comment]
The tab should show up now. Best of luck with your new package!

**Comment by belka-ew** [comment]
It wasn't there first, but after 15 minutes the tab shows up. Thanks a lot, you are the best! ;)
